###
GET http://localhost:8081/api/pacientes HTTP/1.1










###
POST http://localhost:8081/api/pacientes HTTP/1.1
Content-Type: application/json

 {
    "idNumeroCedula": 654,
    "nombre": "Maribel",
    "apellido": "Juarez",
    "telefono": "31145678"
  }


###
GET http://localhost:8081/api/pacientes/0 HTTP/1.1








###
PUT http://localhost:8081/api/pacientes/654 HTTP/1.1
Content-Type: application/json

{
    "idNumeroCedula": 654,
    "nombre": "Juana",
    "apellido": "Juarez",
    "telefono": "31145678"
  }



###
DELETE http://localhost:8081/api/pacientes/0 HTTP/1.1


DOCTORES

//Doctores

###
GET http://localhost:8000/api/doctores HTTP/1.1





















###
POST http://localhost:8081/api/doctores HTTP/1.1
Content-Type: application/json

{   
  "id_profesional": "803",
  "nombre": "Arturo",
  "apellido": "Mendez",
  "correo":"arturo@mail.com",
  "especialidad": "medicina_general"
}









###
GET http://localhost:8000/api/doctores/80345678 HTTP/1.1

###
PUT http://localhost:8000/api/doctores/80345678 HTTP/1.1
Content-Type: application/json

{
    "id_profesional": 80345678,
    "nombre": "Arturo Pepito",
    "apellido": "Mendez",
    "correo": "arturo@mail.com",
    "telefono": "2234567",
    "especialidad": "medicina_interna"
  }









###
DELETE http://localhost:8000/api/doctores/80345678 HTTP/1.1
















//Citas
###
GET http://localhost:8000/api/citas HTTP/1.1




















###
POST http://localhost:8000/api/citas HTTP/1.1
Content-Type: application/json

{   
  "fecha_hora": "2023-10-23T08:01:00.000Z",
      "id_profesional": 71978654,
      "id_numeroCedula": 79978654
}












###
GET http://localhost:8000/api/citas/one-cita?profesional=71978654&paciente=79978654&fecha=2023-11-23T08:13:00.000Z HTTP/1.1

###
PUT http://localhost:8000/api/citas/?profesional=71978654&paciente=79978654&fecha=2023-10-23T08:01:00.000Z HTTP/1.1
Content-Type: application/json

{
    "fecha_hora": "2023-11-23T08:13:00.000Z",
    "id_profesional": 71978654,
    "id_numeroCedula": 79978654
  }










###
DELETE http://localhost:8000/api/citas?profesional=71978654&paciente=79978654&fecha=2023-11-23T08:13:00.000Z HTTP/1.1