###
GET http://localhost:8081/api/pacientes HTTP/1.1










###
POST http://localhost:8081/api/pacientes HTTP/1.1
Content-Type: application/json

{
    "idNumeroCedula": 609,
    "nombre": "Manuela",
    "apellido": "Juarez",
    "telefono": "31145678",
    "fechaNacimiento": "1998-10-09T12:00:00"
  }


###
GET http://localhost:8081/api/pacientes/0 HTTP/1.1








###
PUT http://localhost:8081/api/pacientes/609 HTTP/1.1
Content-Type: application/json

{
    "idNumeroCedula": 0,
    "nombre": "Manuela",
    "apellido": "Juarez",
    "telefono": "31145678",
    "fechaNacimiento": "2000-10-09T12:00:00"
  }





###
DELETE http://localhost:8081/api/pacientes/609 HTTP/1.1










DOCTORES

//Doctores

###
GET http://localhost:8081/api/doctores HTTP/1.1


###
GET http://localhost:8081/api/doctores/especialidad/medicina_general HTTP/1.1



















###
POST http://localhost:8081/api/doctores HTTP/1.1
Content-Type: application/json

{   
  "idProfesional": 939,
  "nombre": "Juan",
  "apellido": "Perez",
  "correo":"arturo@mail.com",
  "especialidad": "medicina_general"
}









###
GET http://localhost:8081/api/doctores/503 HTTP/1.1

###
PUT http://localhost:8081/api/doctores/503 HTTP/1.1
Content-Type: application/json

{
  "idProfesional": 503,
  "nombre": "Arturo",
  "apellido": "Perez",
  "correo": "arturo@mail.com",
  "especialidad": "medicina_interna"
}








###
DELETE http://localhost:8081/api/doctores/703 HTTP/1.1
















//Citas
###
GET http://localhost:8000/api/citas HTTP/1.1




















###
POST http://localhost:8000/api/citas HTTP/1.1
Content-Type: application/json

{   
  "fecha_hora": "2023-10-23T08:01:00.000Z",
      "id_profesional": 71978654,
      "id_numeroCedula": 79978654
}












###
GET http://localhost:8000/api/citas/one-cita?profesional=71978654&paciente=79978654&fecha=2023-11-23T08:13:00.000Z HTTP/1.1

###
PUT http://localhost:8000/api/citas/?profesional=71978654&paciente=79978654&fecha=2023-10-23T08:01:00.000Z HTTP/1.1
Content-Type: application/json

{
    "fecha_hora": "2023-11-23T08:13:00.000Z",
    "id_profesional": 71978654,
    "id_numeroCedula": 79978654
  }










###
DELETE http://localhost:8000/api/citas?profesional=71978654&paciente=79978654&fecha=2023-11-23T08:13:00.000Z HTTP/1.1